//AUTH
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL';
export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';

//DIAGNOSTIC FORM
export const GET_AVAILABLE_TESTS = 'GET_AVAILABLE_TESTS';
export const LOAD_TEST_TO_STORE = 'LOAD_TEST_TO_STORE';
export const LOAD_SAT_CONVERSION_TO_STORE = 'LOAD_SAT_CONVERSION_TO_STORE';
export const SET_LOADING_TEST_STATUS = 'SET_LOADING_TEST_STATUS';
export const LOG_USER_ANSWER = 'LOG_USER_ANSWER';
export const POST_USER_ANSWERS = 'POST_USER_ANSWERS';
export const SET_DIAGNOSTIC_IN_PROGRESS_STATUS =
  'SET_DIAGNOSTIC_IN_PROGRESS_STATUS';
