//////////////////
// ACTION TYPES //
//////////////////

export const CLIENT_PROFILES_LOADING = 'CLIENT_PROFILES_LOADING';
export const CLIENT_PROFILE_LOADING = 'CLIENT_PROFILE_LOADING';
export const CLIENT_PROFILES_LOADED = 'CLIENT_PROFILES_LOADED';
export const CLIENT_PROFILE_LOADED = 'CLIENT_PROFILE_LOADED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

export default {
  CLIENT_PROFILES_LOADING,
  CLIENT_PROFILE_LOADING,
  CLIENT_PROFILES_LOADED,
  CLIENT_PROFILE_LOADED,
  AUTHENTICATION_ERROR
};
