# Generated by Django 2.0 on 2018-07-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_questiontype_question_type_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiontype',
            options={'ordering': ['question_type', 'question_type_group']},
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='question_type',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterUniqueTogether(
            name='questiontype',
            unique_together={('question_type', 'question_type_group')},
        ),
    ]
