# Generated by Django 2.0 on 2018-07-20 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('client_type', models.CharField(max_length=50)),
                ('enrollment_status', models.CharField(max_length=50)),
                ('pay_rate', models.IntegerField()),
                ('purchased_hours', models.IntegerField()),
                ('delivered_hours', models.IntegerField()),
                ('focus_area_1', models.CharField(blank=True, max_length=150, null=True)),
                ('focus_area_2', models.CharField(blank=True, max_length=150, null=True)),
                ('focus_area_3', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('parent_email', models.EmailField(max_length=254)),
                ('SAT_diagnostic_score', models.IntegerField(blank=True, null=True)),
                ('SAT_diagnostic_reading_writing', models.IntegerField(blank=True, null=True)),
                ('SAT_diagnostic_math', models.IntegerField(blank=True, null=True)),
                ('SAT_diagnostic_essay', models.CharField(blank=True, max_length=25, null=True)),
                ('SAT_best_practice', models.IntegerField(blank=True, null=True)),
                ('SAT_best_practice_reading_writing', models.IntegerField(blank=True, null=True)),
                ('SAT_best_practice_math', models.IntegerField(blank=True, null=True)),
                ('SAT_best_practice_essay', models.CharField(blank=True, max_length=25, null=True)),
                ('SAT_best_official', models.IntegerField(blank=True, null=True)),
                ('SAT_best_official_reading_writing', models.IntegerField(blank=True, null=True)),
                ('SAT_best_official_math', models.IntegerField(blank=True, null=True)),
                ('SAT_best_official_essay', models.CharField(blank=True, max_length=25, null=True)),
                ('LSAT_diagnostic_score', models.IntegerField(blank=True, null=True)),
                ('LSAT_best_practice', models.IntegerField(blank=True, null=True)),
                ('LSAT_best_official', models.IntegerField(blank=True, null=True)),
                ('ACT_diagnostic_score', models.IntegerField(blank=True, null=True)),
                ('ACT_best_practice', models.IntegerField(blank=True, null=True)),
                ('ACT_best_official', models.IntegerField(blank=True, null=True)),
                ('colleges_accepted', models.TextField(blank=True, null=True)),
                ('college_matriculated', models.TextField(blank=True, null=True)),
                ('scholarship_awarded', models.TextField(blank=True, null=True)),
                ('law_schools_accepted', models.TextField(blank=True, null=True)),
                ('law_school_matriculated', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_profiles',
            },
        ),
    ]
