# Generated by Django 2.0 on 2018-07-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_clientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
