# Generated by Django 2.0 on 2018-07-06 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_questiontypegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='question_type_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.QuestionTypeGroup'),
            preserve_default=False,
        ),
    ]
