# Generated by Django 2.0 on 2018-07-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180720_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='id',
            new_name='client',
        ),
    ]
