# Generated by Django 2.0 on 2018-07-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('tutor', 'tutor'), ('client', 'client'), ('public', 'public')], default='public', max_length=25),
        ),
    ]
