//////////////////
// ACTION TYPES //
//////////////////

export const GET_AVAILABLE_TESTS = 'GET_AVAILABLE_TESTS';
export const LOAD_TEST_TO_STORE = 'LOAD_TEST_TO_STORE';
export const LOAD_SAT_CONVERSION_TO_STORE = 'LOAD_SAT_CONVERSION_TO_STORE';
export const SET_LOADING_TEST_STATUS = 'SET_LOADING_TEST_STATUS';
export const LOG_USER_ANSWER = 'LOG_USER_ANSWER';
export const POST_USER_ANSWERS = 'POST_USER_ANSWERS';
export const SET_DIAGNOSTIC_IN_PROGRESS_STATUS =
  'SET_DIAGNOSTIC_IN_PROGRESS_STATUS';
export const SET_STEP = 'SET_STEP';
export const SET_SELECTED_TEST = 'SET_SELECTED_TEST';

export default {
  GET_AVAILABLE_TESTS,
  LOAD_TEST_TO_STORE,
  LOAD_SAT_CONVERSION_TO_STORE,
  SET_LOADING_TEST_STATUS,
  LOG_USER_ANSWER,
  POST_USER_ANSWERS,
  SET_DIAGNOSTIC_IN_PROGRESS_STATUS,
  SET_STEP,
  SET_SELECTED_TEST
};
