//////////////////
// ACTION TYPES //
//////////////////

export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL';
export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const PASSWORD_RESET_SENT = 'PASSWORD_RESET_SENT';
export const PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';

export default {
  AUTHENTICATION_ERROR,
  LOGIN_SUCCESSFUL,
  LOGIN_FAILED,
  LOGOUT_SUCCESSFUL,
  REGISTRATION_SUCCESSFUL,
  REGISTRATION_FAILED,
  PASSWORD_RESET_SENT,
  PASSWORD_RESET_FAILED,
  PASSWORD_RESET_SUCCESS,
  USER_LOADING,
  USER_LOADED
};
